name: bilateral-gp
channels:
  - conda-forge
dependencies:
  - ninja
  - python
  - pip
  - pip:
    - jupyterlab
    - ipywidgets
    - tqdm
    - fire
    - seaborn
    - altair
    - numpy
    - scipy
    - pandas
    - torch
    - scikit-learn
    - gpytorch
    - wandb
    - pykeops
