name: bgp
channels:
  - conda-forge
dependencies:
  - ninja
  - python=3.7
  - pip
  - pip:
    - jupyterlab
    - ipywidgets
    - numpy
    - scipy
    - scikit-learn
    - altair
    - seaborn
    - tqdm
    - fire
    - tensorboard
    - 'torch -f https://download.pytorch.org/whl/cu102/torch_stable.html'
    - gpytorch
    - wandb
