name: bilateral-gp
channels:
  - conda-forge
  - anaconda
dependencies:
  # - cmake  ## Only install on demand.
  - ninja
  - python
  - pip
  - pip:
    - jupyterlab
    - ipywidgets
    - tqdm
    - fire
    - seaborn
    - altair
    - numpy
    - scipy
    - pandas
    - 'torch<1.8'
    - scikit-learn
    - gpytorch
    - wandb
    - pykeops
