name: bgp
channels:
  - conda-forge
dependencies:
  - ninja
  - python=3.7
  - pip
  - pip:
    - jupyterlab
    - ipywidgets
    - numpy
    - scipy
    - scikit-learn
    - altair
    - seaborn
    - tqdm
    - fire
    - tensorboard
    - torch
    - gpytorch
    - 'wandb<0.10.0'
