# method: grid
# method: bayes
# metric:
#   name: val/lik
#   goal: maximize

method: random
parameters:
  dataset:
    value: 3droad
  lr:
    value: 0.01
  epochs:
    value: 100
  lanc_iter:
    value: 100
  pre_size:
    value: 100
program: experiments/train_bigp.py
# program: experiments/train_skip.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}