method: grid
parameters:
  dataset:
    values:
      - pumadyn32nm_all
      - protein
      - houseelectric
      - 3droad
      - kin40k_all
      - keggdirected
  lr:
    value: 0.01
  epochs:
    value: 100
  lanc_iter:
    value: 100
  pre_size:
    value: 100
program: experiments/train_bigp.py
# program: experiments/train_skip.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
