## Datasets with small N.

# method: grid
# method: bayes
# metric:
#   name: val/lik
#   goal: maximize

method: grid
parameters:
  dataset:
    value: 3droad
  lr:
    values: [0.01, 0.05, 0.1]
  epochs:
    value: 200
  lanc_iter:
    values: [30, 50, 100, 200, 300, 400, 500]
  pre_size:
    values: [0, 10]
program: experiments/train_bigp.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}

