name: BiGP
method: grid
parameters:
  dataset:
    values:
      - elevators_all
      - houseelectric
      - keggdirected
      # - kin40k_all
      - precipitation3d_all
      - protein
  epochs:
    value: 1000
  p_epochs:
    value: 200
  lr:
    values:
      - 0.1
  lanc_iter:
    values:
      - 100
  pre_size:
    values:
      - 100
  nu:
    values:
      - 1.5
  order:
    values:
      - 1
      # - 2
      # - 3
program: experiments/train_bigp.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}