# method: random
method: grid
parameters:
  dataset:
    values:
      - elevators
      - houseelectric
      - keggdirected
      - precipitation3d_all
  epochs:
    value: 100
  lr:
    value: 0.05
  lanc_iter:
    value: 100
  pre_size:
    value: 20
program: experiments/train_bigp.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}