name: cubench
# method: random
method: grid
parameters:
  dataset:
    values:
      - elevators_all
      - houseelectric
      - keggdirected
      - kin40k_all
      - precipitation3d_all
      - protein
program: experiments/cuda_test.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}