# method: grid
# method: bayes
# metric:
#   name: val/lik
#   goal: maximize

method: random
parameters:
  dataset:
    value: 3droad
  lr:
    value: 0.1
  epochs:
    value: 100
  lanc_iter:
    value: 30
  pre_size:
    value: 10
program: experiments/train_bigp.py
# program: experiments/train_skip.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}