name: simplex-gp
method: grid
parameters:
  dataset:
    values:
      - 3droad
      # - elevators
      - houseelectric
      # - keggdirected
      - precipitation3d_all
      # - protein
  epochs:
    value: 100
  p_epochs:
    value: 200
  lr:
    values:
      - 0.1
  lanc_iter:
    values:
      - 100
  pre_size:
    values:
      - 100
  nu:
    values:
      - None
      - 1.5
  min_noise:
    values:
      - 0.0001
      # - 0.001
      # - 0.01
      - 0.1
  # seed:
  #   values:
  #     - -1
  #     - -2
  #     - -3
program: experiments/train_keops.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
