name: sgpr-m512
method: grid
parameters:
  dataset:
    values:
      - elevators
      # - houseelectric
      - keggdirected
      - precipitation3d_all
      - protein
  epochs:
    value: 1000
  p_epochs:
    value: 200
  lr:
    values:
      - 0.1
  lanc_iter:
    values:
      - 100
  pre_size:
    values:
      - 100
  n_inducing:
    values:
      - 512
  nu:
    values:
      - None
      - 1.5
  # seed:
  #   values:
  #     - -1
  #     - -2
  #     - -3
program: experiments/train_sgpr.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}