name: SGPR
method: grid
parameters:
  dataset:
    values:
      - elevators_all
      - houseelectric
      - keggdirected
      - kin40k_all
      - precipitation3d_all
      - protein
  epochs:
    value: 200
  lr:
    values:
      - 0.01
  lanc_iter:
    value: 100
  pre_size:
    value: 10
  n_inducing:
    values:
      - 512
program: experiments/train_sgpr.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}