name: simplex-gp
method: grid
parameters:
  dataset:
    values:
      - 3droad
      - elevators
      - houseelectric
      - keggdirected
      - precipitation3d_all
      - protein
  epochs:
    value: 100
  p_epochs:
    value: 200
  lr:
    values:
      - 0.1
  cg_iter:
    values:
      - 500
      # - 1000
  lanc_iter:
    values:
      - 100
  pre_size:
    values:
      - 100
  nu:
    values:
      - 1.5
  order:
    values:
      - 1
      # - 2
      # - 3
  min_noise:
    values:
      # - 0.0001
      - 0.1
  # seed:
  #   values:
  #     - -1
  #     - -2
  #     - -3
  #     - -4
  #     - -5
program: experiments/train_bigp.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
