name: skip-m9
method: grid
parameters:
  dataset:
    values:
      - elevators_all
      - houseelectric
      - keggdirected
      - precipitation3d_all
      - protein
  epochs:
    value: 1000
  p_epochs:
    value: 200
  lr:
    values:
      - 0.1
  lanc_iter:
    values:
      - 100
  pre_size:
    values:
      - 100
  grid_size:
    values:
      - 9
  nu:
    values:
      - None
      # - 1.5
  seed:
    values:
      - -1
      - -2
      - -3
program: experiments/train_skip.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}