# method: bayes
# metric:
#   name: val/lik
#   goal: maximize

method: grid
parameters:
  dataset:
    value: 3droad
  lr:
    value: 0.1
  epochs:
    value: 200
  lanc_iter:
    values: [30, 50, 100, 200]
  pre_size:
    values: [0, 10]
program: experiments/train_skip.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}