## Datasets with small N.

# method: grid
# method: bayes
# metric:
#   name: val/lik
#   goal: maximize

method: random
parameters:
  dataset:
    value: 3droad
  lr:
    value: 0.1
  epochs:
    value: 200
  log_int:
    value: 1
  lanc_iter:
    values: [20, 30, 40, 50, 60]
program: experiments/train_skip.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
