name: SKIP
method: grid
parameters:
  dataset:
    values:
      - elevators_all
      - keggdirected
      - kin40k_all
      # - precipitation3d_all
      - protein
  epochs:
    value: 1000
  p_epochs:
    value: 200
  lr:
    values:
      - 0.1
  lanc_iter:
    values:
      - 100
  pre_size:
    values:
      - 100
  grid_size:
    values:
      - 10
  nu:
    values:
      - 1.5
program: experiments/train_skip.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}